### ISSUE TITLE
real recording timing is shorter than expected recording timing

### ISSUE THREAD

**Issue by crypto623** [shaynet10/puppeteer-video-recorder#1]
```
const puppeteer = require('puppeteer');
const PuppeteerVideoRecorder = require('puppeteer-video-recorder');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  page.setViewport({
    width: 1800,
    height: 800,
    deviceScaleFactor: 1,
  });
  page.setDefaultNavigationTimeout(0);
  await page.goto('http://google.com');
  const recorder = new PuppeteerVideoRecorder();
  setTimeout(async () => {
    await recorder.stop();
    await browser.close();
  }, 10000)
})();
```
As you can see, expected recording timing is 10s, but real recording timing is around 1s.
"dependencies": {
    "puppeteer": "^7.1.0",
    "puppeteer-video-recorder": "^1.0.3"
  }
and ffmpeg versin is 4.3.2-2021-02-20-full_build-www.gyan.dev

please help me.

**Comment by shaynet10** [comment]
Hi code friend,
Let me first of all say thank you for sharing this issue with me.
I'm happy to see that others find this code useful.

Regarding to your question.
The short answer is, both of my packages depand on Google casting algorithm, and since they send new frames only for changes made on the screen, and you don't perform any change on screen after your login, you'll get only the time of login in your video.

In some more details for geeks :)
Puppeteer video recording, is just a simple tool that combines ffmpeg with screenshots returned from
Puppeteer mass screenshots.

And puppeteer mass screenshots, creates a screenshot every time Chrome sends a frame.
And basically, Chrome sends a frame/few frames every time it detects that something was changed in the UI.

I hope it explains better why you see only 1 second.

Again thanks for the issue.

**Comment by crypto623** [comment]
Thank you @shaynet10 
One more question :)
Can I record the video and audio with this one? or only screens?

**Comment by shaynet10** [comment]
Only screens.
Sorry 😐

**Comment by shaynet10** [comment]
I'll close the issue, hoping my info was helpful.

**Comment by euberdeveloper** [comment]
You can actually manually inject a spinner or something small that changes with puppeteer.

This way chrome should send frames regularly

**Comment by arash-bizcover** [comment]
@euberdeveloper how do you do that ? inject a spinner in
Do you have puppeteer code for it?

**Comment by arash-bizcover** [comment]
Found a way 

```js

await page.evaluate(showSpinner)


function showSpinner(img = INJECTED_LOADING_GIF_URL) {
    let spin_div = document.createElement("div")
    spin_div.id = "spinner"
    spin_div.setAttribute("class", "spinner")
    spin_div.style.cssText = `position: fixed; top: 1%; left: 1%; z-index: 510; background-color: #fff; padding: 26px; -moz-border-radius: 4px; -webkit-border-radius: 4px; border-radius: 4px; background-image: url(${img});`
    document.body.append(spin_div);
}
```

**Comment by euberdeveloper** [comment]
Yes, that's it. Not a clean solution, anyway
